### ISSUE TITLE
dosnt work

### ISSUE THREAD

**Issue by PronsMods** [Bbalduzz/Valorant-Account-Creator#2]
i use the premium one press generate and cmd opens wait 2-30 seconds try to login and it saying i cant that the acc dosnt exist probably ratted

**Comment by Bbalduzz** [comment]
did u used the exe?
Cause the releases are outdated. Use the CLI version instead (they are in the ValogenPremium folder)

**Comment by RealThreat** [comment]
yo ! do you have discord please for some info
